### PR TITLE
Daos warning fixes

### PR DESCRIPTION
**Pull request by roblatham00**
I'd appreciate @mchaarawi reviewing these changes -- I kind of just smashed things around until the warnings (gcc-11.2.0 on sunspot against DAOS-2.2 ) went away.

### CODE REVIEW

**Comment by roblatham00** [comment]
Sorry that wasn't gcc-11.2 that was intel's OneAPI compiler, version 2024.x.0.20231009

**Comment by mchaarawi** [comment]
> I'd appreciate @mchaarawi reviewing these changes -- I kind of just smashed things around until the warnings (gcc-11.2.0 on sunspot against DAOS-2.2 ) went away.

I’ve had this pr open for a while https://github.com/hpc/ior/pull/467 that hasn’t been landed yet. I think it addresses some of the warnings, but maybe not all.

**Comment by JulianKunkel** [comment]
@mchaarawi It seems there are some conflicts with the previous PR, since I cannot do testing, I hope you can resolve it!
Happy XMas!

**Comment by mchaarawi** [comment]
> @mchaarawi It seems there are some conflicts with the previous PR, since I cannot do testing, I hope you can resolve it! Happy XMas!

since this is @roblatham00 's PR, i did a merge in his branch and resolved the conflicts here: https://github.com/roblatham00/ior/pull/1
once that is merged, this PR will be updated

**Comment by roblatham00** [comment]
Hah! I don't care which branch gets merged just want daos driver in good
shape on main

**Comment by roblatham00** [comment]
pull request updated with Mohamad's fixes.

**Pull request merged**
