### PR TITLE
Update tutorial.rst

### PR DESCRIPTION
**Pull request by haplav**
"Defeating Page Cache" should be a heading I guess.

### CODE REVIEW

**Comment by JulianKunkel** [comment]
thanks for contributing, any more thoughts on documntation, maybe?

Am Do., 16. Mai 2019 um 19:51 Uhr schrieb Vaclav Hapla
<notifications@github.com>:
>
> "Defeating Page Cache" should be a heading I guess.
>
> ________________________________
>
> You can view, comment on, or merge this pull request online at:
>
>   https://github.com/hpc/ior/pull/151
>
> Commit Summary
>
> Update tutorial.rst
>
> File Changes
>
> M doc/sphinx/userDoc/tutorial.rst (1)
>
> Patch Links:
>
> https://github.com/hpc/ior/pull/151.patch
> https://github.com/hpc/ior/pull/151.diff
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.



-- 
Dr. Julian Kunkel
Lecturer, Department of Computer Science
+44 (0) 118 378 8218
http://www.cs.reading.ac.uk/
https://hps.vi4io.org/
PGP Fingerprint: 1468 1A86 A908 D77E B40F 45D6 2B15 73A5 9D39 A28E

**Comment by glennklockwood** [comment]
I actually have a branch with significant edits to the documentation (https://github.com/glennklockwood/ior/tree/docfixes), but it is now out of sync with the current master.  I can rebase it and try to update the documentation as best I can, but it will need help from the community to spot places where new features haven't been captured.

**Comment by haplav** [comment]
> thanks for contributing, any more thoughts on documntation, maybe? Am Do., 16. Mai 2019 um 19:51 Uhr schrieb Vaclav Hapla <notifications@github.com>:
> […](#)

If I find something again, I will get back to you. But dor now I would just propose to put the link to https://ior.readthedocs.io/en/latest/index.html somewhere clearly to GitHub, probably README.md.

Today I first got to http://wiki.lustre.org/IOR where I spent some time before I noticed it was completely outdated and the mentioned GitHub repository archived. Then got to this GitHub repo where I found [doc/USER_GUIDE](doc/USER_GUIDE). And only now in the evening I noticed the readthedocs docs, only thanks to the issue mentioning it. Please just take it as a hint for improvement.

Anyway, thanks for maintaining this tool.

**Comment by glennklockwood** [comment]
This is good feedback, and I agree that the documentation is currently all over the place (multiple README files, a manpage, a USER_GUIDE, etc).  I'll create an issue so we can track this more closely.

**Comment by haplav** [comment]
Sounds good!

**Comment by haplav** [comment]
One more specific comment: It is not clear from docs whether Lustre stripe settings are applied even to a pre-existing file (done by copying it to a temporary file with the that stripe settings). But looking at the source code I don't think so, and in that case it should be explicitly mentioned in docs or implemented as above, I believe.

**Pull request merged**
