### PR TITLE
Add median MiB and OPs results

### PR DESCRIPTION
**Pull request by jyvet**
Context: Detailed summary displays the mean over all
iteratons for every operations. The mean may vary
a lot between multiple runs.

This patch adds the median in the detailed summary.

### CODE REVIEW

**Comment by JulianKunkel** [comment]
Thanks for submitting the suggestions.
I find it cumbersome to add more and more statistics, particularly when they involve more code and sorting. Instead I'd prefer we output the individual values and have users compute whatever they want (Median, Q90), who knows... Don't know what do the others think?

**Comment by glennklockwood** [comment]
I tend to agree with @JulianKunkel on this.  As long as the results from each iteration are printed, users can calculate whatever percentile they'd like.  Ideally #33 (json output) would simplify the process for downstream analysis to do these sorts of calculations so that IOR itself doesn't have to present them.

**Comment by jyvet** [comment]
Thanks for your comments. I like the idea of having a JSON output. Maybe, it would also help to simplify current IOR code to remove some stats and improve code clarity. If so, it would be neat to embed a script (python?) which parses that output, computes and displays basic statistics.

**Comment by JulianKunkel** [comment]
@Jean-Yves, that would be great!
Please have a look at the testing branch, I believe the JSON output (a
minor revision happened yesterday) should fit your needs.
Python script would be nice!

How to use it is described here: https://github.com/hpc/ior/pull/33
(As said, the format of the file slightly changed, but gives an impression)

**Pull request closed without merging**
