### PR TITLE
WIP: randomized datapackettype

### PR DESCRIPTION
**Pull request by glennklockwood**
This branch supports full block scrambling using the [golden prime method implemented in elbencho](https://github.com/breuner/elbencho/blob/master/source/toolkits/random/RandAlgoGoldenPrime.h#L39).  I verified that the resulting file is much less compressible than the "incompressible" data packet type.  For example, writing a 1 MiB file in 4 KiB blocks, then gzipping it (default parameters) results in the following compressed sizes:

- 10772 bytes for `-l incompressible` in ior-3.3
- 11470 bytes for `-l incompressible` in master (commit a436395)
- 1045698 bytes for `-l random` in this branch

There is a lot missing from this branch so far:

- [x] confirmation that this datapackettype is supported in mdtest and md-workbench
- [x] confirmation that `ior -h` reports it as an option (should probably check mdtest and md-workbench too)
- [x] quantification of performance regression with this datapackettype - there probably is some
- [ ] updated documentation
- [ ] add this datapackettype to the travis tester
- [ ] sanity checks for different compilers and platforms

I opened this WIP PR just so I don't lose track of progress here.

### CODE REVIEW

**Comment by JulianKunkel** [comment]
That's great. It will in some cases come with a performance hit, though.
To support it in any tool, extend in utilities.c:206 parsePacketType(char t)
Also, the documentation for the options can be changed. 
Glad the refactoring of the code helped.

**Comment by glennklockwood** [comment]
Comparing the performance of different dataPacketTypes for sequential and random (`-z`) IOR runs against an NVMe file system (single client) with page cache enabled shows that this new dataPacketType does induce a ~10% performance penalty on writes.

```
pattern: seq (incompressible vs. timestamp)
128m            : 2967.5 MiB/s (incompressible) vs. 3009.4 MiB/s (timestamp) (1.4% difference)
1m              : 3039.6 MiB/s (incompressible) vs. 3029.1 MiB/s (timestamp) (-0.3% difference)
4k              : 2532.3 MiB/s (incompressible) vs. 2495.2 MiB/s (timestamp) (-1.5% difference)

pattern: rand (incompressible vs. timestamp)
128m            : 3012.6 MiB/s (incompressible) vs. 2988.2 MiB/s (timestamp) (-0.8% difference)
1m              : 3072.5 MiB/s (incompressible) vs. 3012.5 MiB/s (timestamp) (-2.0% difference)
4k              : 2522.1 MiB/s (incompressible) vs. 2529.4 MiB/s (timestamp) (0.3% difference)

pattern: seq (random vs. timestamp)
128m            : 2662.0 MiB/s (random) vs. 3009.4 MiB/s (timestamp) (11.5% difference)
1m              : 2731.4 MiB/s (random) vs. 3029.1 MiB/s (timestamp) (9.8% difference)
4k              : 2261.2 MiB/s (random) vs. 2495.2 MiB/s (timestamp) (9.4% difference)

pattern: rand (random vs. timestamp)
128m            : 2719.1 MiB/s (random) vs. 2988.2 MiB/s (timestamp) (9.0% difference)
1m              : 2731.0 MiB/s (random) vs. 3012.5 MiB/s (timestamp) (9.3% difference)
4k              : 2328.3 MiB/s (random) vs. 2529.4 MiB/s (timestamp) (8.0% difference)
```

Curiously, elbencho suffers much less performance impact between its equivalent `dataPacketType`s (`--blockvaralgo fast` and `--blockvarpct 0`/`--blockvarpct 100`):

```
pattern: seq (random vs. timestamp)
128m            : 2793.8 MiB/s (random) vs. 2996.8 MiB/s (timestamp) (6.8% difference)
1m              : 2921.1 MiB/s (random) vs. 3026.2 MiB/s (timestamp) (3.5% difference)
4k              : 2594.4 MiB/s (random) vs. 2750.8 MiB/s (timestamp) (5.7% difference)

pattern: rand (random vs. timestamp)
128m            : 2812.4 MiB/s (random) vs. 2979.2 MiB/s (timestamp) (5.6% difference)
1m              : 2926.6 MiB/s (random) vs. 3089.8 MiB/s (timestamp) (5.3% difference)
4k              : 2635.8 MiB/s (random) vs. 2786.7 MiB/s (timestamp) (5.4% difference)
```

Maybe this is because elbencho has a lower baseline peak bandwidth than IOR, but the absolute MiB/s for, e.g., 1m writes, indicates that this `--dataPacketType=random` is slower than it could be.

**Comment by glennklockwood** [comment]
@breuner recommended a modification that closes the performance gap of `-l random` between IOR and elbencho which I applied in e1208a6.  The new performance is:

```
pattern: seq (incompressible vs. timestamp)
128m            : 3007.5 MiB/s (incompressible) vs. 3013.2 MiB/s (timestamp) (0.2% difference)
1m              : 3080.4 MiB/s (incompressible) vs. 3098.2 MiB/s (timestamp) (0.6% difference)
4k              : 2521.0 MiB/s (incompressible) vs. 2597.4 MiB/s (timestamp) (2.9% difference)

pattern: rand (incompressible vs. timestamp)
128m            : 3027.1 MiB/s (incompressible) vs. 3001.0 MiB/s (timestamp) (-0.9% difference)
1m              : 3097.9 MiB/s (incompressible) vs. 3044.7 MiB/s (timestamp) (-1.7% difference)
4k              : 2570.4 MiB/s (incompressible) vs. 2577.5 MiB/s (timestamp) (0.3% difference)

pattern: seq (random vs. timestamp)
128m            : 2787.7 MiB/s (random) vs. 3013.2 MiB/s (timestamp) (7.5% difference)
1m              : 2916.6 MiB/s (random) vs. 3098.2 MiB/s (timestamp) (5.9% difference)
4k              : 2387.4 MiB/s (random) vs. 2597.4 MiB/s (timestamp) (8.1% difference)

pattern: rand (random vs. timestamp)
128m            : 2828.8 MiB/s (random) vs. 3001.0 MiB/s (timestamp) (5.7% difference)
1m              : 2918.5 MiB/s (random) vs. 3044.7 MiB/s (timestamp) (4.1% difference)
4k              : 2460.0 MiB/s (random) vs. 2577.5 MiB/s (timestamp) (4.6% difference)
```

I am satisfied with this and will update the documentation.

**Comment by adilger** [comment]
One question about the "random" data pattern used - does this clobber/conflict with the "datestamp" pattern?  It is very useful for debugging to have a pattern written into the data blocks that can be mapped back to a specific rank/offset.

IMHO, keeping the rank+offset+timestamp at the start of each block/chunk even with "random" shouldn't affect the compressibility noticeably, since the rest of the block will be filled with random data, but it would make debugging IO problems *much* easier.

**Review by JulianKunkel — APPROVED** [review]

**Comment by JulianKunkel** [comment]
In order to make some progress with testing and prevent further backmerges, I merged this patch.

**Pull request merged**
